<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>WeatherCrawler</RootNamespace>
    <AssemblyName>WeatherCrawler</AssemblyName>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Weather\Weather.csproj" />
  </ItemGroup>

</Project>
