<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>Weather</RootNamespace>
    <AssemblyName>Weather</AssemblyName>
    <Nullable>disable</Nullable>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TaskScheduler" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="Selenium.WebDriver" />
    <PackageReference Include="Selenium.Support" />
    <PackageReference Include="Serilog" />
  </ItemGroup>

</Project>
